# File: .github/workflows/data-cron.yml
name: Auto Update OmniStats Data

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    # Thêm biến môi trường này để ép GitHub dùng Node.js 24 theo chuẩn mới nhất
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Chạy Script Kéo API
        run: node update-data.js
        
      - name: Commit và Push file JSON mới lên web
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add live-matches.json
          git commit -m "Auto-update: Đồng bộ dữ liệu thể thao mới nhất" || exit 0
          git push
